name: Retrain Movie Model

on:
  push:
    paths:
      - 'data/**'        # Runs if files in the data folder change
  workflow_dispatch:      # Allows you to click a button in GitHub to run it manually
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run training script
        run: python main.py

      - name: Commit and push updated models
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add models/*.pkl
          git commit -m "Auto-retrain: Update recommendation models" || echo "No changes to commit"
          git push